agenda/urls.py
from django.urls import path
from .views import agendar, agendaDay, agend, deletarAgend, deletarAgendDia, editarAgend, editarAgendDia

urlpatterns = [
    path('agendar/', agendar, name='agendar'),
    path('dia/', agendaDay, name="AgendaDia"),
    path('ver/', agend, name="agendaTotal"),
    path('dia/editar/<int:pk>', editarAgendDia, name="editarAgendaDoDia"),
    path('dia/deletar/<int:pk>', deletarAgendDia, name="deletarAgendaDoDia"),
    path('ver/editar/<int:pk>', editarAgend, name="editarAgenda"),
    path('ver/deletar/<int:pk>', deletarAgend, name="deletarAgenda"),
]

central/urls.py
from django.contrib import admin
from django.urls import path, include
from dashboard.views import index, delEspe
from agenda.views import agendar
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('paciente/', include('paciente.urls')),
    path('medico/', include('medico.urls')),
    path('agenda/', include('agenda.urls')),
    path('', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('dashboard/', index, name="dashboard"),
    path('agenda/agendar', agendar, name="agendar"),
    path('deletarEspe/<int:pk>', delEspe, name="deletarEspecializacao")
]

agenda/models.py
from django.db import models
from paciente.models import paciente
from medico.models import medico, especializacao
import datetime

class agenda(models.Model):
    nomeMedico = models.ForeignKey(medico, blank=True, null=True, on_delete=models.SET_NULL)
    nomePaciente = models.ForeignKey(paciente, on_delete=models.CASCADE)
    especializacao = models.ForeignKey(especializacao, null=True, blank=True, on_delete=models.SET_NULL)
    data = models.DateField()
    hora = models.TimeField()

    def __str__(self):
        return "{} - {} - {}".format(self.nomePaciente, self.nomeMedico, self.especializacao)

dashboard/models.py
from django.db import models

# Create your models here.

medico/models.py
from django.db import models


class especializacao(models.Model):
    nome = models.CharField(max_length=300, null=True)

    def __str__(self):
        return self.nome
        
class medico(models.Model):
    nome = models.CharField(max_length=300, unique=True)
    crm = models.CharField(max_length=300)
    especializacao = models.ForeignKey(especializacao, blank=True, null=True, on_delete=models.SET_NULL)
    rg = models.CharField(max_length=60, unique=True)
    cpf = models.CharField(max_length=80, unique=True)
    celular = models.CharField(max_length=80)
    telefone = models.CharField(max_length=80, blank=True)
    estado = models.CharField(max_length=300)
    cidade = models.CharField(max_length=300)
    sangue = models.CharField(max_length=300, blank=True)
    endereco = models.CharField(max_length=300)
    email = models.EmailField()

    def __str__(self):
        return self.nome

paciente/models.py
from django.db import models
from medico.models import medico

class paciente(models.Model):
    Nome = models.CharField(max_length=300, unique=True)
    rg = models.CharField(max_length=60, unique=True)
    cpf = models.CharField(max_length=80, unique=True)
    celular = models.CharField(max_length=80)
    telefone = models.CharField(max_length=80, blank=True)
    estado = models.CharField(max_length=300)
    cidade = models.CharField(max_length=300)
    sangue = models.CharField(max_length=300, blank=True)
    endereco = models.CharField(max_length=300)
    email = models.EmailField()

    def __str__(self):
        return self.Nome

class adicionarAtendimento(models.Model):
    nomePaciente = models.ForeignKey(paciente, blank=True, on_delete=models.CASCADE)
    nomeMedico = models.ForeignKey(medico, null=True, blank=True, on_delete=models.SET_NULL)
    data = models.DateField()
    hora = models.TimeField()
    descricao = models.TextField()

    def __str__(self):
        return '{} - {}'.format(self.nomePaciente, self.nomeMedico)

agenda/forms.py
from django.forms import ModelForm, DateInput, TimeInput,DateField
from .models import agenda
from paciente.models import paciente
from medico.models import medico

class agendaForm(ModelForm):
    class Meta:
        model = agenda
        fields = '__all__'
        widgets = {
            'data': DateInput(attrs={'class': 'datepicker'}),
            'hora': TimeInput(attrs={'type': 'time'})
        }

agenda/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import agendaForm
from .models import agenda
from datetime import date
from django.contrib.auth.decorators import login_required


@login_required
def agendar(request):
    form = agendaForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('/agenda/agendar/')

    return render(request, "agendar.html", {'form':form})

@login_required
def agendaDay(request):
    nome = request.GET.get('search', None)

    if nome:
        agendaDia = agenda.objects.filter(nomePaciente__Nome__contains=nome, data=date.today())
    else:
        agendaDia = agenda.objects.filter(data=date.today())


    database={
        'agenda':agendaDia
    }

    return render(request, 'agendaDia.html', database)


@login_required
def agend(request):
    nome = request.GET.get('search', None)

    if nome:
        agendaTotal = agenda.objects.filter(nomePaciente__Nome__contains=nome)
    else:
        agendaTotal = agenda.objects.filter()


    database={
        'agenda':agendaTotal
    }

    return render(request, 'agenda.html', database)

@login_required
def deletarAgendDia(request, pk):
    agenda.objects.filter(id=pk).delete()

    return redirect('/agenda/dia/')

@login_required
def editarAgendDia(request,pk):
    agend = agenda.objects.get(id=pk)

    if request.method == "POST":
        form = agendaForm(request.POST, instance=agend)
        if form.is_valid():
            form.save()
            return redirect('/agenda/dia/')
    else:
        form = agendaForm(instance=agend)


    return render(request, 'editAgendaDia.html', {'form':form})


@login_required
def deletarAgend(request, pk):
    agenda.objects.filter(id=pk).delete()

    return redirect('/agenda/ver/')

@login_required
def editarAgend(request,pk):
    agend = agenda.objects.get(id=pk)
    
    type(agend.data)
        

    print(agend.data)

    if request.method == "POST":
        form = agendaForm(request.POST, instance=agend)
        if form.is_valid():
            form.save()
            return redirect('/agenda/ver/')
    else:
        form = agendaForm(instance=agend)


    return render(request, 'editarAgenda.html', {'form':form})


    

dashboard/views.py
from django.shortcuts import render
from datetime import date
from django.http import HttpResponseRedirect
from medico.form import medicoForm, especializacaoForm
from medico.models import medico, especializacao
from paciente.models import paciente
from agenda.models import agenda
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    pacientes = paciente.objects.all()
    medicos = medico.objects.all()
    form = especializacaoForm(request.POST or None)
    especialidades = especializacao.objects.all()
    agendaHoje = agenda.objects.filter(data=date.today())

    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/dashboard/')

    database ={
        'form':form,
        'especialidades':especialidades,
        'numeroPacientes':pacientes.count(),
        'numeroMedicos':medicos.count(),
        'numeroAtendimentos':agendaHoje.count(),
    }
    return render(request, "dashboard.html", database)

@login_required
def delEspe(request, pk):
    especializacao.objects.get(id=pk).delete()

    return HttpResponseRedirect('/dashboard/')

templates/agenda.html
{% extends "base.html" %}
{% block name_title %}Agenda{% endblock %}
{% load static %}
{% block link_css %}
{% endblock %}

{% block content %}
{% include 'nav.html' %}

    <nav class="container light-blue lighten-3">
        <div class="nav-wrapper">
        <form>
            <div class="input-field">
            <input id="search" type="search" name="search" required>
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i class="material-icons">close</i>
            </div>
        </form>
        </div>
    </nav>


    <table class="container">
        <thead>
          <tr>
              <th>Nome Paciente</th>
              <th>Médico</th>
              <th>Especialização</th>
              <th>Data</th>
              <th>Hora</th>
              <th>Ações</th>
          </tr>
        </thead>

{% for age in agenda %}
        <tbody>
          <tr>
            <td>{{ age.nomePaciente }}</td>
            <td>{{ age.nomeMedico }}</td>
            <td>{{ age.especializacao }}</td>
            <td>{{ age.data }}</td>
            <td>{{ age.hora }}</td>
            <td>
            <a href="{% url 'editarAgenda' age.id %}"><i class="material-icons" style="color: black">edit</i></a>
            <a href="{% url 'deletarAgenda' age.id %}"><i class="material-icons" style="color:red">delete_sweep</i></a>
            </td>
          </tr>
        </tbody>
{% endfor %}
      </table>


{% endblock %}

templates/agendar.html
{% extends "base.html" %}
{% block name_title %}Agendar{% endblock %}
{% load static %}
{% block link_css %}
<link type="text/css" rel="stylesheet" href="{% static "css/agendar.css" %}"
{% endblock %}

{% block content %}
{% include 'nav.html' %}
    <form action="{% url 'agendar' %}" method="post" class="container">
        {% csrf_token %}
        <div class="row">
            <div class="col s6">
                <label>Nome do medico (opcional): </label>
                {{ form.nomeMedico }}
            </div>
            <div class="col s6">
                <label>Nome do paciente: </label>
                {{ form.nomePaciente }}
            </div>
            <div class="col s6">
                <label>Especialidade (opcional): </label>
                {{ form.especializacao }}
            </div>
            <div class="col s6">
                <label>Data do atendimento: </label>
                {{ form.data }}
            </div>
            <div class="col s6">
                <label>Hora do atendimento: </label>
                {{ form.hora }}
            </div>
        </div>
        <input type="submit" value="Agendar">
    </form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "css/materialize.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
    <title>
    {% block name_title %}{% endblock %}
    </title>
    {% block link_css %}{% endblock %}
</head>
<body>

    {% block content %}{% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="{% static "js/materialize.min.js" %}"></script>
    <script>
    $(document).ready(function(){
        $('.sidenav').sidenav();
        $('select').formSelect();
        $(".dropdown-trigger").dropdown();
        $('.modal').modal();
        $('.datepicker').datepicker({
            format: 'dd/mm/yyyy',
                i18n: {
                months: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
                monthsShort: ["Jan", "Feb", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dez"],
                weekdays: ["Domingo","Segunda", "Terça", "Quart", "Quinta", "Sexta", "Sábado"],
                weekdaysShort: ["Dom","Seg", "Ter", "Qua", "Qui", "Sex", "Sab"],
                weekdaysAbbrev: ["D","S", "T", "Q", "Q", "S", "S"]
            }
        });
    });
    </script>
    {% block link_js %}{% endblock %} 
</body>
</html>

templates/buscarMedico.html
{% extends "base.html" %}
{% block name_title %}Buscar Médico{% endblock %}
{% load static %}
{% block link_css %}
{% endblock %}

{% block content %}
{% include 'nav.html' %}

    <nav class="container light-blue lighten-3">
        <div class="nav-wrapper">
        <form>
            <div class="input-field">
            <input id="search" type="search" name="search" required>
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i class="material-icons">close</i>
            </div>
        </form>
        </div>
    </nav>


    <table class="container">
        <thead>
          <tr>
              <th>Nome</th>
              <th>Ações</th>
          </tr>
        </thead>

{% for medico in medicos %}
        <tbody>
          <tr>
            <td>{{ medico.nome }}</td>
            <td>
            <a href="{% url 'editarMedico' medico.id %}"><i class="material-icons" style="color: black">edit</i></a>
            <a href="{% url 'deletarMedico' medico.id %}"><i class="material-icons" style="color:red">delete_sweep</i></a>
            </td>
          </tr>
        </tbody>
{% endfor %}
      </table>


{% endblock %}

templates/buscarPaciente.html
{% extends "base.html" %}
{% block name_title %}Buscar paciente{% endblock %}
{% load static %}
{% block link_css %}
{% endblock %}

{% block content %}
{% include 'nav.html' %}

    <nav class="container light-blue lighten-3">
        <div class="nav-wrapper">
        <form>
            <div class="input-field">
            <input id="search" name="search" type="search" required>
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i class="material-icons">close</i>
            </div>
        </form>
        </div>
    </nav>

    <table class="container">
        <thead>
          <tr>
              <th>Nome</th>
              <th>Ações</th>
          </tr>
        </thead>

{% for paciente in pacientes %}

        <tbody>
          <tr>
            <td>{{ paciente.Nome }}</td>
            <td>
            <a href="{% url 'verPaciente' paciente.id %}"><i class="material-icons" style="color: black">person</i></a>
            <a href="{% url 'editarPaciente' paciente.id %}"><i class="material-icons" style="color: black">edit</i></a>
            <a href="{% url 'deletarPaciente' paciente.id %}"><i class="material-icons" style="color:red">delete_sweep</i></a>
            </td>
          </tr>
        </tbody>
    
{% endfor %}    
      </table>
{% endblock %}

templates/criarMedico.html
{% extends "base.html" %}
{% block name_title %}Adicionar Médico{% endblock %}
{% load static %}
{% block link_css %}<link type="text/css" rel="stylesheet" href="{% static 'css/criarMedico.css' %}">{% endblock %}

{% block content %}

    {% include 'nav.html' %}

    <form action="{% url 'criarMedico' %}" method="post" class="container">
        {% csrf_token %}
        <h4>Dados do médico</h4>
        <div class="divider"></div>
        <div class="row">
            <div class="col m8 s12">
                <label for="id_Nome">Nome do médico</label>
                {{ form.nome }}
            </div>
            <div class="col m2 s6">
                <label for="id_Nome">Especialização</label>
                {{ form.especializacao }}
            </div>
            <div class="col m2 s6">
                <label for="id_Nome">CRM</label>
                {{ form.crm }}
            </div>
            <div class="col m4 s6">
                <label for="id_rg">RG</label>
                {{ form.rg }}
            </div>
            <div class="col m4 s6">
                <label for="id_cpf">CPF</label>
                {{ form.cpf }}
            </div>
            <div class="col m4 s6">
                <label for="id_celular">Celular</label>
                {{ form.celular }}
            </div>
            <div class="col m4 s6">
                <label for="id_telefone">Telefone (opcional)</label>
                {{ form.telefone }}
            </div>
            <div class="col m4 s6">
                <label for="id_sangue">Tipo sanguíneo (opcional)</label>
                {{ form.sangue }}
            </div>
            <div class="col m4 s6">                
                <label for="id_email">E-mail</label>
                {{ form.email }}
            </div>
        </div>
        <h4>Localização</h4>
        <div class="divider"></div>
        <div class="row">
            <div class="col m12 s12">                
                <label for="id_endereco">Endereço</label>
                {{ form.endereco }}
            </div>
            <div class="col s6">                
                <label for="id_cidade">Cidade</label>
                {{ form.cidade }}
            </div>
            <div class="col s6">                
                <label for="id_estado">Estado</label>
                {{ form.estado }}
            </div>
        </div>
        <input type="submit" value="Cadastrar">
    </form>
{% endblock %}

templates/dashboard.html
{% extends "base.html" %}
{% block name_title %}Início{% endblock %}
{% load static %}
{% block link_css %}<link type="text/css" rel="stylesheet" href="{% static 'css/dashboard.css' %}">{% endblock %}

{% block content %}

{% include "nav.html" %}

<div class="container">
    <div class="row">
        <div class="col m4 s12"> 

            <div class="card-panel teal z-depth-4">
                <span class="white-text"><i class="material-icons" style="font-size:70px">account_circle</i>
                <span style="font-size:16px">Atendimentos: {{numeroAtendimentos}}</span> 
                </span>
            </div>
        
        </div>
        <div class="col m4 s12"> 

            <div class="card-panel grey z-depth-4">
                <span class="white-text"><i class="material-icons" style="font-size:70px">face</i>
                <span style="font-size:16px">Pacientes: {{numeroPacientes}}</span> 
            </div>
        
        </div>
        
        <div class="col m4 s12"> 

            <div class="card-panel teal z-depth-4">
                <span class="white-text"><i class="material-icons" style="font-size:70px">portrait</i>
                <span style="font-size:16px">Médicos: {{numeroMedicos}}</span> 
            </div>
        
        </div>
        
    </div>

        <div class="row">

            <div class="col m2 s6 center"> 

                <a href="{% url 'criarPaciente' %}">
                    <div class="card-panel light-blue lighten-3 center">
                            <p class="white-text"><i class="material-icons" style="font-size:40px">account_circle</i></p>
                            <p style="font-size:12px" class="white-text">Criar paciente</p>    
                    </div>
                </a>

            </div>

            <div class="col m2 s6 center"> 

                <a href="{% url 'buscarPaciente' %}">
                    <div class="card-panel light-blue lighten-3 center">
                            <p class="white-text"><i class="material-icons" style="font-size:40px">assignment_ind</i></p>
                            <p style="font-size:12px" class="white-text">Buscar Paciente</p>    
                    </div>
                </a>

            </div>

            <div class="col m2 s6 center"> 

                <a href="{% url 'criarMedico' %}">
                    <div class="card-panel light-blue lighten-3 center">
                        
                            <p class="white-text"><i class="material-icons" style="font-size:40px">portrait</i></p>
                            <p style="font-size:12px" class="white-text">Criar médico</p> 
    
                    </div>
                </a>

            </div>

            <div class="col m2 s6 center"> 

                <a href="{% url 'buscarMedico' %}">
                    <div class="card-panel light-blue lighten-3 center">
                        
                            <p class="white-text"><i class="material-icons" style="font-size:40px">person</i></p>
                            <p style="font-size:12px" class="white-text">Buscar médico</p> 
    
                    </div>
                </a>

            </div>
        

            <div class="col m2 s6 center"> 

                <a href="{% url 'agendar' %}">
                    <div class="card-panel light-blue lighten-3 center">
                            <p class="white-text"><i class="material-icons" style="font-size:40px">add_comment</i></p>
                            <p style="font-size:12px" class="white-text">Agendar</p>   
                    </div>
                </a>

            </div>

            <div class="col m2 s6 center"> 

                <a href="{% url 'AgendaDia' %}">
                    <div class="card-panel light-blue lighten-3 center">
                            <p class="white-text"><i class="material-icons" style="font-size:40px">file_copy</i></p>
                            <p style="font-size:12px" class="white-text">Agenda do dia</p>   
                    </div>
                </a>

            </div>

            <div class="col m2 s6 center"> 

                <a class="modal-trigger" href="#criarEspecialidade">
                    <div class="card-panel light-blue lighten-3 center">
                            <p class="white-text"><i class="material-icons" style="font-size:40px">note_add</i></p>
                            <p style="font-size:12px" class="white-text">Criar especialidade</p>   
                    </div>
                </a>

            </div>

            <div id="criarEspecialidade" class="modal">
                <div class="modal-content">
                <h5>Adicionar especialidade</h5>
                <form method="POST">
                {% csrf_token %}
                    <label for="id_Nome">Especialização</label>
                    {{form.nome}}
                </div>
                <div class="modal-footer">
                <input type="submit" class="btn" value="Cadastrar">
                </form>
                </div>
            </div>

            <div class="col m2 s6 center"> 

                <a class="modal-trigger" href="#especialidade">
                    <div class="card-panel light-blue lighten-3 center">
                            <p class="white-text"><i class="material-icons" style="font-size:40px">event_note</i></p>
                            <p style="font-size:12px" class="white-text">Ver especialidades</p>   
                    </div>
                </a>

            </div>

            <div id="especialidade" class="modal">
                <div class="modal-content">
                <h5>Especialidades</h5>
                    <table class="container">
                        <thead>
                        <tr>
                            <th>Especialidades</th>
                            <th>Ações</th>
                        </tr>
                        </thead>

                {% for especialidade in especialidades %}
                        <tbody>
                        <tr>
                            <td>{{ especialidade.nome }}</td>
                            <td>
                            <a href="{% url 'deletarEspecializacao' especialidade.id %}"><i class="material-icons" style="color:red">delete_sweep</i></a>
                            </td>
                        </tr>
                        </tbody>
                {% endfor %}
                </div>
            </div>

    </div>
</div>

{% endblock %}

templates/editAgendaDia.html
{% extends "base.html" %}
{% block name_title %}Editar Agenda do dia{% endblock %}
{% load static %}
{% block link_css %}
<link type="text/css" rel="stylesheet" href="{% static "css/agendar.css" %}"
{% endblock %}

{% block content %}
{% include 'nav.html' %}
    <form method="post" class="container">
        {% csrf_token %}
        <div class="row">
            <div class="col s6">
                <label>Nome do medico (opcional): </label>
                {{ form.nomeMedico }}
            </div>
            <div class="col s6">
                <label>Nome do paciente: </label>
                {{ form.nomePaciente }}
            </div>
            <div class="col s6">
                <label>Especialidade (opcional): </label>
                {{ form.especializacao }}
            </div>
            <div class="col s6">
                <label>Data do atendimento: </label>
                {{ form.data }}
            </div>
            <div class="col s6">
                <label>Hora do atendimento: </label>
                {{ form.hora }}
            </div>
        </div>
        <input type="submit" value="Editar">
    </form>
{% endblock %}

templates/editMedic.html
{% extends "base.html" %}
{% block name_title %}Editar médico{% endblock %}
{% load static %}
{% block link_css %}<link type="text/css" rel="stylesheet" href="{% static 'css/criarMedico.css' %}">{% endblock %}

{% block content %}

    {% include 'nav.html' %}

    <form method="post" class="container">
        {% csrf_token %}
        <h4>Dados do médico</h4>
        <div class="divider"></div>
        <div class="row">
            <div class="col m8 s12">
                <label for="id_Nome">Nome do médico</label>
                {{ form.nome }}
            </div>
            <div class="col m2 s6">
                <label for="id_Nome">Especialização</label>
                {{ form.especializacao }}
            </div>
            <div class="col m2 s6">
                <label for="id_Nome">CRM</label>
                {{ form.crm }}
            </div>
            <div class="col m4 s6">
                <label for="id_cpf">RG</label>
                {{ form.rg }}
            </div>
            <div class="col m4 s6">
                <label for="id_cpf">CPF</label>
                {{ form.cpf }}
            </div>
            <div class="col m4 s6">
                <label for="id_celular">Celular</label>
                {{ form.celular }}
            </div>
            <div class="col m4 s6">
                <label for="id_telefone">Telefone (opcional)</label>
                {{ form.telefone }}
            </div>
            <div class="col m4 s6">
                <label for="id_sangue">Tipo sanguíneo (opcional)</label>
                {{ form.sangue }}
            </div>
            <div class="col m4 s6">                
                <label for="id_email">E-mail</label>
                {{ form.email }}
            </div>
        </div>
        <h4>Localização</h4>
        <div class="divider"></div>
        <div class="row">
            <div class="col m12 s12">                
                <label for="id_endereco">Endereço</label>
                {{ form.endereco }}
            </div>
            <div class="col s6">                
                <label for="id_cidade">Cidade</label>
                {{ form.cidade }}
            </div>
            <div class="col s6">                
                <label for="id_estado">Estado</label>
                {{ form.estado }}
            </div>
        </div>
        <input type="submit" value="Editar">
    </form>
{% endblock %}

templates/editarPacient.html
{% extends "base.html" %}
{% block name_title %}Editar paciente{% endblock %}
{% load static %}
{% block link_css %}
<link type="text/css" rel="stylesheet" href="{% static "css/criarPaciente.css" %}"
{% endblock %}

{% block content %}

    {% include 'nav.html' %}

    <form method="post" class="container">
        {% csrf_token %}
        <h4>Dados do paciente</h4>
        <div class="divider"></div>
        <div class="row">
            <div class="col s12">
                <label for="id_Nome">Nome paciente</label>
                {{ form.Nome }}
            </div>
            <div class="col m4 s6">
                <label for="id_rg">RG</label>
                {{ form.rg }}
            </div>
            <div class="col m4 s6">
                <label for="id_cpf">CPF</label>
                {{ form.cpf }}
            </div>
            <div class="col m4 s6">
                <label for="id_celular">Celular</label>
                {{ form.celular }}
            </div>
            <div class="col m4 s6">
                <label for="id_telefone">Telefone (opcional)</label>
                {{ form.telefone }}
            </div>
            <div class="col m4 s6">
                <label for="id_sangue">Tipo sanguíneo (opcional)</label>
                {{ form.sangue }}
            </div>
            <div class="col m4 s6">                
                <label for="id_email">E-mail</label>
                {{ form.email }}
            </div>
        </div>
        <h4>Localização</h4>
        <div class="divider"></div>
        <div class="row">
            <div class="col m12 s12">                
                <label for="id_endereco">Endereço</label>
                {{ form.endereco }}
            </div>
            <div class="col s6">                
                <label for="id_cidade">Cidade</label>
                {{ form.cidade }}
            </div>
            <div class="col s6">                
                <label for="id_estado">Estado</label>
                {{ form.estado }}
            </div>
        </div>
        <input type="submit" value="Editar">
    </form>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block name_title %}Login{% endblock %}
{% load static %}
{% block link_css %}<link type="text/css" rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock %}

{% block content %}

<div class="container">
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

templates/verFicha.html
{% extends "base.html" %}
{% block name_title %}Buscar paciente{% endblock %}
{% load static %}
{% block link_css %}
{% endblock %}

{% block content %}
{% include 'nav.html' %}

<div class="container" style="margin-top:25px">
    {% for atendimento in atendimentos %}
      <div class="card-panel teal z-depth-4">
          <span class="white-text">
          <span style="font-size:16px">Médico: {{ atendimento.nomeMedico }}</span><br>
          <span style="font-size:16px">Data: {{ atendimento.data }}</span><br>
          <span style="font-size:16px">Hora: {{ atendimento.hora }}</span> <br>
          <span style="font-size:16px">Descrição: {{ atendimento.descricao }}</span>
          </span>
      </div>
    {% endfor %}
</div>

<a class="modal-trigger btn-floating btn-large waves-effect waves-light green" style="position:fixed; right:20px; bottom: 20px;" href="#modal1"><i class="material-icons">add</i></a>

  <div id="modal1" class="modal">
    <div class="modal-content">
      <h5>Adicionar atendimento</h5>
    </div>
    {% for pessoa in pessoas %}
    <form action="{% url 'adicionarAtendimento' pessoa.id %}" method="post" class="container">
  
    {% csrf_token %}
      <div class="col s12">
        <label for="id_Nome">Nome do médico</label>
          {{ form.nomeMedico }}
      </div>
      <div class="col s12">
        <label for="id_Nome">Data</label>
          {{ form.data }}
      </div>
      <div class="col s12">
        <label for="id_Nome">Hora</label>
          {{ form.hora }}
      </div>
      <div class="col s12">
        <label for="id_Nome">Descrição</label>
          {{ form.descricao }}
      </div>
        <div class="modal-footer">
            <input type="submit" value="Adicionar">
        </div>
    </form>
    {% endfor %}
  </div>

{% endblock %}